# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1a66e6b707c4059e321d4875a01115da8ff6751ae7f6eba6ce571dfcfff8010569279605a816fcb9a3ab83a387508c943210f6f9ba281e2a7e56ca7f6c687ad

test:
  secret_key_base: c282e263492a24508bffbf7abf171e8f48c508d8b0bc64c36b6dd42a0563374a502b6f099833f1cb0ff90804f2e37aefb0e8a72dd83ce17e87954f1d3aef15be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
